/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\
/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\
/////                                                  \\\\\
///// Use enchantment of the launcher to determine     \\\\\
///// what to hit: Crossbows                           \\\\\
/////                                                  \\\\\
/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\
/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\

/////                                                  \\\\\
///// Only for weapons usable by the player            \\\\\
/////                                                  \\\\\

INCLUDE ~%MOD_FOLDER%/lib/launcher_functions.tph~

LAF ENCHANT_LAUNCHERS
INT_VAR
  enchant_bows = 0
  enchant_crossbows = 1
  enchant_slings = 0
  player_only = 1
END
