/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\
/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\
/////                                                  \\\\\
///// Add damage bonus to bows                         \\\\\
/////                                                  \\\\\
/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\
/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\/////\\\\\

/////                                                  \\\\\
///// Half bonus to weapons usable by the player       \\\\\
/////                                                  \\\\\

INCLUDE ~%MOD_FOLDER%/lib/launcher_functions.tph~

// launcher damage check: abort if damage bonus already exists
LAF BOW_HAS_DAMAGE_BONUS RET result END
ACTION_IF (result) BEGIN
  ABORT @1004 // Damage bonus is already applied.
END

LAF APPLY_BOW_DAMAGE_BONUS
INT_VAR
  player_only = 2
  factor_nominator = 1
  factor_denominator = 2
  factor_rounding = 1
END
