INCLUDE ~%MOD_FOLDER%/lib/a7_wed_lib.tph~

COPY_EXISTING ~ar3000.tis~ ~override~
  READ_LONG 0x0c tile_size
  PATCH_IF (tile_size == 12) BEGIN
    // patching PVRZ-based tileset
    INNER_ACTION BEGIN
      // installing safe chest pvrz
      OUTER_SET pvrz_index = 20
      OUTER_FOR (i = 20; i < 100; ++i) BEGIN
        ACTION_IF (NOT FILE_EXISTS_IN_GAME ~ar3000%i%.pvrz~) BEGIN
          OUTER_SET pvrz_index = i
          OUTER_SET i = 100
        END
      END
      COPY ~%MOD_FOLDER%/pvrz/bg2ee/a300020.pvrz~ ~override/a3000%pvrz_index%.pvrz~
    END

    // patching safe chest into ar3000.tis
    SET $tis_coords(~1583~) = 0   | (0 << 16)
    SET $tis_coords(~1584~) = 64  | (0 << 16)
    SET $tis_coords(~1585~) = 128 | (0 << 16)
    SET $tis_coords(~1625~) = 0   | (64 << 16)
    SET $tis_coords(~1626~) = 64  | (64 << 16)
    SET $tis_coords(~1627~) = 128 | (64 << 16)
    READ_LONG 0x10 ofs_tiles
    PHP_EACH tis_coords AS index => coord BEGIN
      SET ofs = ofs_tiles + index * tile_size
      WRITE_LONG ofs pvrz_index
      SET x = coord & 0xffff
      SET y = (coord >> 16) & 0xffff
      WRITE_LONG (ofs + 4) x
      WRITE_LONG (ofs + 8) y
    END
  END ELSE PATCH_IF (tile_size == 5120) BEGIN
    // patching palette-based tileset
    DEFINE_ASSOCIATIVE_ARRAY tis_coords BEGIN
      // start tile index, number of tiles to add => file to insert
      1583, 3 => ~safe_chest_tiles-row1.dat~
      1625, 3 => ~safe_chest_tiles-row2.dat~
    END
    READ_LONG 0x10 ofs_tiles
    PHP_EACH tis_coords AS pos => filename BEGIN
      SET index = $pos(~0~)
      SET count = $pos(~1~)
      SET ofs = ofs_tiles + index * tile_size
      WRITE_FILE ofs ~%MOD_FOLDER%/tis/%filename%~
    END
  END ELSE BEGIN
    PATCH_ABORT @1005 // Unsupported tileset format detected: AR3000.TIS
  END
BUT_ONLY

ACTION_IF (is_bg2 || is_bgt) BEGIN
  COPY ~%MOD_FOLDER%/mos/ar3000.mos~ ~override~

  // original games may crash if certain relevant area files are not found in the override folder
  WITH_SCOPE BEGIN
    ACTION_FOR_EACH filename IN ~ar3000ht.bmp~ ~ar3000lm.bmp~ ~ar3000sr.bmp~ BEGIN
      ACTION_IF (FILE_EXISTS_IN_GAME ~%filename%~) BEGIN
        OUTER_SET $files(~%filename%~) = 1
      END
    END

    COPY_EXISTING ~ar3000.are~ ~override~
      GET_OFFSET_ARRAY amb_offsets ARE_V10_AMBIENTS
      PHP_EACH amb_offsets AS _ => ofs BEGIN
        READ_SHORT (ofs + 0x80) count
        FOR (i = 0; i < count; ++i) BEGIN
          READ_ASCII (ofs + 0x30 + i * 8) resref (8) NULL
          PATCH_IF (FILE_EXISTS_IN_GAME ~%resref%.wav~) BEGIN
            TO_LOWER ~resref~
            SET $files(~%resref%.wav~) = 1
          END
        END
      END
      READ_LONG 0xbc ofs_songs
      PATCH_FOR_EACH ofs IN 0x28 0x30 0x3c 0x44 BEGIN
        READ_ASCII (ofs_songs + ofs) resref (8) NULL
        PATCH_IF (FILE_EXISTS_IN_GAME ~%resref%.wav~) BEGIN
          TO_LOWER ~resref~
          SET $files(~%resref%.wav~) = 1
        END
      END
    BUT_ONLY

    ACTION_PHP_EACH files AS file => _ BEGIN
      COPY_EXISTING ~%file%~ ~override~
    END
  END
END

// patching area
COPY_EXISTING ~ar3000.are~ ~override~
  // adding container
  PATCH_WITH_SCOPE BEGIN
    SET $fj_vertex(~0~) = 1952 | (2420 << 16)
    SET $fj_vertex(~1~) = 1985 | (2440 << 16)
    SET $fj_vertex(~2~) = 1985 | (2459 << 16)
    SET $fj_vertex(~3~) = 1968 | (2471 << 16)
    SET $fj_vertex(~4~) = 1938 | (2452 << 16)
    SET $fj_vertex(~5~) = 1938 | (2432 << 16)
    SET $fj_vertex(~6~) = 1944 | (2425 << 16)
    LPF fj_are_structure
      INT_VAR
        fj_loc_x = 1924
        fj_loc_y = 2476
        fj_type = 2   // chest
        fj_trap_loc_x = 1959
        fj_trap_loc_y = 2446
        fj_box_left = 1938
        fj_box_top = 2420
        fj_box_right = 1985
        fj_box_bottom = 2471
      STR_VAR
        fj_structure_type = ~container~
        fj_name = ~a7-safe_chest~
    END
  END

  // adding fake door (for impeded cell blocks)
  PATCH_WITH_SCOPE BEGIN
    SET $fj_cell_open_vert(~0~) = 120 | (203 << 16)
    SET $fj_cell_open_vert(~1~) = 121 | (203 << 16)
    SET $fj_cell_open_vert(~2~) = 121 | (204 << 16)
    SET $fj_cell_open_vert(~3~) = 122 | (204 << 16)
    SET $fj_cell_open_vert(~4~) = 122 | (205 << 16)
    SET $fj_cell_open_vert(~5~) = 123 | (205 << 16)
    LPF fj_are_structure
      INT_VAR
        fj_flags = BIT0 | BIT5 | BIT9 // Door open, Cannot close, Can be looked through
        fj_open_box_left = 0
        fj_open_box_top = 0
        fj_open_box_right = 1
        fj_open_box_bottom = 1
        fj_closed_box_left = 0
        fj_closed_box_top = 0
        fj_closed_box_right = 1
        fj_closed_box_bottom = 1
      STR_VAR
        fj_structure_type = ~door~
        fj_name = ~a7-safe_chest~
        fj_door_wed_id = ~A7_CHEST~
    END
  END

  // adding map note
  LPF fj_are_structure
    INT_VAR
      fj_loc_x = 2000
      fj_loc_y = 2420
      fj_note_strref = RESOLVE_STR_REF(@2400) // Safe Chest
      fj_color = (is_bg2ee || is_eet) ? 2 : 4 // red
    STR_VAR
      fj_structure_type = ~note~
  END
BUT_ONLY

// adding new WED door structure (required for oBG2, optional for BG2EE)
COPY_EXISTING ~ar3000.wed~ ~override~
  LPF a7#wed_open RET success RET_ARRAY wed END
  PATCH_IF (success) BEGIN
    LPF a7#batch_wed_add_door
      STR_VAR
        door_name = ~A7_CHEST~
      RET success
      RET_ARRAY wed
    END
  END
  PATCH_IF (success) BEGIN
    LPF a7#wed_close RET success END
  END ELSE BEGIN
    PATCH_ABORT @1006 // Could not patch file: AR3000.WED
  END
BUT_ONLY
