IF
  !Global("Severed_Hand_Reveal","GLOBAL",0)
  Global("a7#beacon_added","MYAREA",0)
  !StateCheck(Player1,STATE_REALLY_DEAD)
  AreaCheckObject("AR2100",Player1)
  Delay(1)
THEN
  RESPONSE #100
    SetGlobal("a7#beacon_added","MYAREA",1)
    ClearAllActions()
    CreateVisualEffectObject("icblesai",Player1)
    DisplayStringHead(Player1,@2210)  // The Great Oak grants you the blessing of nature.
    ActionOverride(Player1,AddSpecialAbility("a7#beac1"))
    Continue()
END
